// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxLxp-lsShW0yV9K6JAkJpdjWMGlTO2ZM',
    appId: '1:969578461985:web:3f5ca48181e9f8f1531c60',
    messagingSenderId: '969578461985',
    projectId: 'my--app-9cc81',
    authDomain: 'my--app-9cc81.firebaseapp.com',
    storageBucket: 'my--app-9cc81.appspot.com',
    measurementId: 'G-DJ35GNM16H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyDbQxvq-yr1qwbVdlLLmoCHGPJGLzmIo',
    appId: '1:969578461985:android:228e0e767a562301531c60',
    messagingSenderId: '969578461985',
    projectId: 'my--app-9cc81',
    storageBucket: 'my--app-9cc81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTyW6x05to3ma8UKabCmjdc3YrKBCLtU0',
    appId: '1:969578461985:ios:55119ed4f5aeddb9531c60',
    messagingSenderId: '969578461985',
    projectId: 'my--app-9cc81',
    storageBucket: 'my--app-9cc81.appspot.com',
    iosBundleId: 'com.example.dumyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTyW6x05to3ma8UKabCmjdc3YrKBCLtU0',
    appId: '1:969578461985:ios:a8902a3c5be61e14531c60',
    messagingSenderId: '969578461985',
    projectId: 'my--app-9cc81',
    storageBucket: 'my--app-9cc81.appspot.com',
    iosBundleId: 'com.example.dumyApp.RunnerTests',
  );
}
